### ISSUE TITLE
Missing items from 'resources' list

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/networking-lessons#14]
https://github.com/raspberrypilearning/networking-lessons/blob/master/README.md lists the only electronic-components required as "Four female-to-female header leads and one LED (lesson 2 only)" but https://github.com/raspberrypilearning/networking-lessons/blob/master/lesson-2/teacher-instructions.md has a more complete list of "Four female-to-female header leads
A 270 ohm resistor
An LED
A button (or paperclip or similar)"

Although looking at the hardware-pictures on https://github.com/raspberrypilearning/networking-lessons/blob/master/lesson-2/student-instructions-2.md (which I assume will be update to the 'new style' at some point) it's not clear how the resistor is connected to the LED - unless the requirements are changed to needing 5 female-to-female jumper leads?

**Comment by bennuttall** [comment]
@LornaLynch is this ok now? Perhaps the caper clip needs to go in `extras.md`?

**Comment by LornaLynch** [comment]
I haven't got this far yet, but I'll check the resources after I've read this lesson's plan properly. I've only skimmed it looking for other stuff so far.

**Comment by LornaLynch** [comment]
OK: I don't think the resistor is needed, as I can't see it referred to in the worksheet or teacher instructions at all. 
I can add the paper clip to `extras.md`, but I do have a problem with the button referred to in the resource. I can't find a suitable image in Components (the Big Red Button and tactile switch don't seem to be what we're looking for), so I'd need @samalderhyde  to provide one. Firstly, though, I'd need @davidhoness or @clivebeale to confirm what sort of button we should be using? 
Additionally, I think the circuit board diagrams in the lesson 2 worksheet are still in the old format?

**Comment by LornaLynch** [comment]
The I can add the resistor into the resources list, but I'd need to how it gets connected into the circuit (what sort of cables are required etc). @davidhoness @clivebeale can you help me out with this?

**Comment by davidhoness** [comment]
Hi folks, I wrote lessons 3 and 4. Clive wrote 1 and 2. But looking at the button used in lesson two, it doesn't really matter. It can be any kind of push button. The goal is to short the two GPIO pins together somehow and this is probably why a paper clip is mentioned.

There would be many ways to connect it, using a breadboard with male to female jumper wires and the push button legs inserted into the breadboard or even with a female to female jumper wire between the two pins that you just connect and disconnect on one end.

**Comment by LornaLynch** [comment]
Thanks, @davidhoness! 

@clivebeale, at the risk of being a bit thick, I'm afraid I'm not certain enough of the best way to rewrite this section of the resource, as I don't have any experience actually connecting stuff to the GPIO pins yet: could you write a couple of sentences in the student worksheet to clarify how the button/paperclip/other shorting device should be connected to the GPIO pins and the resistor? Could you also clarify how many cables of which sort (F-F, M-F etc) we need in total? Thanks.

**Comment by LornaLynch** [comment]
OK, I think everything in this resource has been checked and fixed, barring the issue above with the button and how it is connected into the circuit. Depending on how this is resolved, the circuit diagram itself might need a little revision. @clivebeale when you have a chance, could you answer my query above?

**Comment by lurch** [comment]
https://github.com/raspberrypilearning/networking-lessons/blob/master/hardware.yml now includes the button, but it still doesn't include the resistor shown in https://www.raspberrypi.org/learning/networking-lessons/lesson-2/worksheet/

**Comment by jonwitts** [comment]
I am going to review the resources list once I have have finished the fourth lesson review. I was thinking of providing a lesson by lesson break down of the additional resources required.

**Comment by martinohanlon** [comment]
This resource has now been archived so I am closing the issue.
